### ISSUE TITLE
Could you please push your reader_test.go and writer_test.go to master?

### ISSUE THREAD

**Issue by GuohuaZhuang** [recogni/tfutils#1]
In ReadMe document, you write the "Usage" has these two test code files, could you please push your reader_test.go and writer_test.go to master?

**Comment by sabhiram** [comment]
Oops - sorry about that, and sorry about not seeing this till today. Not sure why my notification did not ping me :(

Here is a simple example I whipped up, I will fix my tests for public consumption and post them later. 

```
package main

import (
	"log"
	"reflect"

	"github.com/recogni/tfutils"

	tf "tensorflow/core/example"
)

func fatalOnErr(err error) {
	if err != nil {
		log.Fatalf("Fatal error: %s\n", err.Error())
	}
}

func main() {
	r, err := tfutils.NewReader([]string{"./foobar.tfrecord"}, nil)
	fatalOnErr(err)

	bs, err := r.ReadRecord()
	fatalOnErr(err)

	m, err := tfutils.GetFeatureMapFromTFRecord(bs)
	fatalOnErr(err)

	log.Printf("%#v\n", m)
}

```

Hope this helps.

**Comment by sabhiram** [comment]
Also - you can check this repo https://github.com/recogni/sorten which uses this library to read and write various TF records (in parallel etc). Ask questions here and I am happy to help you along.
